services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: laravel-app
    restart: always
    volumes:
      - .:/var/www
    networks:
      - app-network

  caddy:
    image: caddy:latest
    container_name: caddy-server
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
