services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    init: true
    ports:
      - "9090:80"
    networks:
      - docker-network
    env_file: ../.env
